[EPIC ID - ODOO1-8] - Add gradein.order Model, Menu and MenuAction
franco-gareis/gradein_service pull request #34
Opened 2023-11-22 13:47 UTC by franco-gareis

2023-11-22 13:49 UTC, franco-gareis commented
Esto tiene que ser mergeado despues de que el modelo de `gradein.reject.reason` haya sido mergeado, ya que depende de ese modelo

2023-11-22 17:06 UTC, ariel-montenegro commented on addons/gradein/models/gradein_order.py
> +        required=True, string="IMEI", help="IMEI of the equipment to check"
Creo que el imei no debe ser requerido por existir tipos de equipos que no llevan este dato. Ej TV

2023-11-22 17:06 UTC, ariel-montenegro commented on addons/gradein/models/gradein_order.py
> +    image_ids = fields.Many2one(
En este caso la relacion pretende mostrar varias imagenes pero equipo solo admite una. ¿Esta bien el string Imagenes?

2023-11-22 17:06 UTC, ariel-montenegro commented on addons/gradein/models/gradein_order.py
> +    answer_id = fields.Many2one(comodel_name="gradein.answer", string="Respuesta")
¿Porque answer debe estar dos veces en el modelo?

2023-11-22 17:59 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +        required=True, string="IMEI", help="IMEI of the equipment to check"
No se si van a haber mas equipos que telefonos, pero le saco el `required`

2023-11-22 18:02 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +    image_ids = fields.Many2one(
Estaba asi en los criterios de Jira en el issue, de hecho el campo se llama `images_ids` por lo que entiendo que son varias imagenes, aunque lo que decis es verdad solamente se puede cargar una imagen

2023-11-22 18:03 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +    answer_id = fields.Many2one(comodel_name="gradein.answer", string="Respuesta")
Estaba asi en los criterios de Jira, la diferencia es que un campo hace referencia a `respuestas` y otro a `respuesta`

2023-11-23 14:30 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +        required=True, string="IMEI", help="IMEI of the equipment to check"
Imei no es requerido, solo para telefonos

2023-11-24 11:40 UTC, yamil95 approved these changes

2023-11-24 16:47 UTC, ariel-montenegro requested changes

2023-11-24 16:47 UTC, ariel-montenegro commented on addons/gradein/models/gradein_order.py
> +    )
Creo que la relación es o2m porque una orden puede tener muchas imagenes pero una imagen solo perteneceria a una orden.

2023-11-24 16:47 UTC, ariel-montenegro commented on addons/gradein/models/gradein_images.py
> +    )
Faltaria la relacion m2o (en el otro comment lo expico)

2023-11-24 18:32 UTC, merged