[odoo01-45]feat: add validation about how many orders can create an user
franco-gareis/gradein_service pull request #46
Opened 2023-11-24 21:23 UTC by yamil95

2023-11-27 13:46 UTC, ariel-montenegro commented on addons/gradein/models/gradein_order.py
> +                raise ValidationError('El usuario cargo varias ordenes en un periodo de 30 dias')
@yamil95 el pr esta bien solo le cambiaria el mensaje por "El usuario ha superado el limite de ordenes permitidos en un periodo de 30 días"

2023-11-27 13:57 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +                raise ValidationError('El usuario cargo varias ordenes en un periodo de 30 dias')
dale ahora hago el pull de lo ultimo que se mergeo para solucionar conflictos, cambio eso y subo los cambios

2023-11-27 15:35 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +                raise ValidationError('El usuario cargo varias ordenes en un periodo de 30 dias')
modificado :+1:

2023-11-27 17:40 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +            if result > int (self.env['ir.config_parameter'].sudo().get_param('max_orders')):
Podriamos guardar esta linea `int(self.env['ir.config_parameter'].sudo().get_param('max_orders'))` en una variable para que sea mas leible el condicional, algo que se llame tipo `max_days`

2023-11-27 17:40 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +            result = self.env["gradein.order"].search_count([('partner_id','=',record.partner_id.id),('date','>',days_diff),('date','<=',today)])
Podriamos renombrar esta variable a algo mas significativo a lo que es? Algo asi como `monthly_user_orders`

2023-11-27 19:05 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +            result = self.env["gradein.order"].search_count([('partner_id','=',record.partner_id.id),('date','>',days_diff),('date','<=',today)])
modificado :+1:

2023-11-28 00:01 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +            result = self.env["gradein.order"].search_count([('partner_id','=',record.partner_id.id),('date','>',days_diff),('date','<=',today)])
Fijate que hice referencia a la variable que se llama `result` para cambiarle el nombre, antes de actualizar mi comentario, de paso ya que estamos, me gustaria saber que devuelve la variable que se llama `result`

2023-11-28 00:05 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +            monthly_user_orders = datetime.today() - timedelta(days=30)
Habria que pensar cuantas veces se va a modificar esta variable, si es una vez cada dos meses entonces deberia ser una constante y le daria un nombre mejor. `MAX_DAYS_TIMEDELTA`

2023-11-28 15:24 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +            result = self.env["gradein.order"].search_count([('partner_id','=',record.partner_id.id),('date','>',monthly_user_orders),('date','<=',today)])
```suggestion
            monthly_user_orders = datetime.today() - timedelta(days=30)
            result = self.env["gradein.order"].search_count([('partner_id', '=', record.partner_id.id),('date', '>', monthly_user_orders),('date', '<=', datetime.today())])
```

2023-11-28 15:24 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +            max_orders = int (self.env['ir.config_parameter'].sudo().get_param('max_orders'))
```suggestion
            max_orders = int(self.env['ir.config_parameter'].sudo().get_param('max_orders'))
```

2023-11-29 12:14 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +            if result > int (self.env['ir.config_parameter'].sudo().get_param('max_orders')):
modificado :+1:

2023-11-29 12:14 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +            result = self.env["gradein.order"].search_count([('partner_id','=',record.partner_id.id),('date','>',days_diff),('date','<=',today)])
devuelve un entero que hace referencia a la cantidad de registros que cumplen con las condiciones que estan entre corchetes

2023-11-29 12:14 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +            result = self.env["gradein.order"].search_count([('partner_id','=',record.partner_id.id),('date','>',monthly_user_orders),('date','<=',today)])
es una cuestion de estilo ese cambio, me gustaria dejarlo asi y mantener por fuera el "today"

2023-11-29 12:14 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +            monthly_user_orders = datetime.today() - timedelta(days=30)
conceptualmente no deberia ser una constante,  las constantes no deberian tomar una expresion que se evalue en tiempo de ejecucion

2023-11-29 14:12 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> +            max_orders = int (self.env['ir.config_parameter'].sudo().get_param('max_orders'))
modificado :+1:

2023-11-29 14:13 UTC, yamil95 reviewed
modificado

2023-11-29 19:23 UTC, franco-gareis requested changes

2023-11-29 19:23 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> +            monthly_user_orders = datetime.today() - timedelta(days=IS_VALID_FOR)
```suggestion
        MAX_DAYS_TIMEDELTA = timedelta(days=30)
        
        for record in self:
            monthly_user_orders = datetime.today() - MAX_DAYS_TIMEDELTA
```

2023-11-29 19:23 UTC, franco-gareis commented on addons/gradein/models/gradein_order.py
> -        self.price = self.equipment_id.price - total
Ojo con esto, tenes que pulearte los cambios de develop

2023-11-29 19:23 UTC, franco-gareis commented
Por favor revisa de traerte los cambios de Develop para que se sincronice con tu PR

2023-11-29 19:45 UTC, yamil95 commented on addons/gradein/models/gradein_order.py
> -        self.price = self.equipment_id.price - total
modificado :+1:

2023-11-30 15:43 UTC, closed without merging